[tools]
go     = "1.26"
node   = "24"
python = "3.14"
"pipx:redfishtool" = "1.1.8"

[settings]
# nice-to-haves
experimental    = true
idiomatic_version_file_enable_tools = []   # don't auto-read .python-version etc; be explicit
