# https://starship.rs/config/
add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch$git_status\
$kubernetes\
$golang$python$nodejs$rust\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
symbol = "☸ "
style = "bold blue"

[golang]
symbol = " "
[python]
symbol = " "
[nodejs]
symbol = " "
[rust]
symbol = " "

[cmd_duration]
min_time = 2000
format = "[took $duration]($style) "
style = "yellow"
